services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: team-24-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    hostname: rabbitmq
    networks:
      - rabbit-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 60s

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: team-24-api
    ports:
      - "8932:8000"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbit-network

  filter:
    build:
      context: .
      dockerfile: Dockerfile
      target: filter
    container_name: team-24-filter
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbit-network

networks:
  rabbit-network:
    driver: bridge